### ISSUE TITLE
Error (stop): TypeError: Cannot read property 'leave' of null [14:23] End of queue.

### ISSUE THREAD

**Issue by Yue-Charlotte** [k27dong/Ozy#4]
Error (stop): TypeError: Cannot read property 'leave' of null
[14:23]
End of queue.

bot进不了频道

**Comment by k27dong** [comment]
bot是否给了管理员权限呢，如果没有的话是进不了上锁的频道的。

改了stop代码中的一个bug，请问现在这个问题还存在吗。
