### ISSUE TITLE
登录出现问题 填写了所需参数 但是在添加 我喜欢的音乐 到播放列表时 提示 code:20001登陆后才可查看

### ISSUE THREAD

**Issue by zhongzi26** [k27dong/Ozy#5]

**Comment by zhongzi26** [comment]
但是脚本传回了登陆成功的讯息 然而连源码中应该会输出的 登录成功的用户昵称也没有

**Comment by zhongzi26** [comment]
> > > 可以看一下具体的输出吗？
> > 
> > 
> > 另外在我用14版本的node进行 npm install的时候（本人第一次使用nodejs 之前完全没有接触过）
> 
> 这个似乎是npm的问题，在我这边试的时候`7.5.2`可以安装，6点几的版本安装就会出现报错。

这边我重新装了一次系统 Centos7 官方镜像

安装nodejs版本为v14.18.1
npm版本为8.1.0

日志如下

[root@zhongzi26 Ozy-main]# node index.js 
Attempting to login ...
logged in.

#这里是我user了一个朋友 选择了他喜欢的音乐歌单 日志如下
{
  status: 400,
  body: {
    code: 20001,
    message: '登录后才可查看',
    debugInfo: null,
    data: null,
    failData: null,
    msg: '登录后才可查看'
  },
  cookie: [
    'NMTID=00OdKafRUH4RyX2FUs9iNpY9fsbOQQAAAF8ghRXAQ; Max-Age=315360000; Expires=Mon, 13 Oct 2031 03:52:23 GMT; Path=/;'
  ]
}

同时在discord内 机器人没有任何反应 奇怪的是并没有看到Default login error: code ${login_q.body.code}的输出

**Comment by zhongzi26** [comment]
> > > 可以看一下具体的输出吗？
> > 
> > 
> > 没有任何输出 我个人目前只是一个高中生，代码也仅限于最基础的知识，但是稍微阅读了一下发现console.log(User: ${login_q.body.profile.nickname})这句连任何输出也没有，尝试播放付费歌曲时机器人会传回参数 登陆后播放 我试了一下您搭建的机器人 发现也无法播放 您应该可以尝试复现一下 但是您的API项目是能够登陆上去的 也许是密码登录的接口有修改？我并不清楚 因为我只是一个普通的高中生 所以抱歉没法给您提供更多的信息了 运行日志在上周我服务器断电后被我重装了系统 非常抱歉
> 
> 如果看不到这句log应该是因为并没有成功登陆，‘登陆后播放’似乎也是因为这个原因。可以看一下`login_q`具体返回的东西，或者有没有看到`Default login error: code ${login_q.body.code}`的输出内容(api.js :46)？
> 
> 我自己正在跑的这个`ozy`也无法播放应该是付费歌曲的缘故。网易云音乐的api(我用的是[这个](https://github.com/Binaryify/NeteaseCloudMusicApi))是没有办法直接播放需要付费购买的歌曲的，只有登陆了已经购买了歌曲的账号才能直接听付费的歌，这个问题应该是没办法解决的，除非我在自己这边用的账号上也去购买。如果方便的话，可以提供一下歌曲的名字吗？

您好 我让程序输出了一下login_q 内容如下


{
  status: 200,
  body: {
    loginType: 1,
    code: 200,
    account: {
      id: 297255927,
      userName: '1_13011172895',
      type: 1,
      status: 0,
      whitelistAuthority: 0,
      createTime: 1467713293091,
      salt: '[B@31752ffa',
      tokenVersion: 1,
      ban: 0,
      baoyueVersion: 1,
      donateVersion: 0,
      vipType: 11,
      viptypeVersion: 1632440295986,
      anonimousUser: false
    },
    token: '9af7d1ab111a6b5047512b0b1a33d74b078f5591542f65f43c394dd9ec20e203519e07624a9f0053d78b6050a17a35e705925a4e6992f61d07c385928f88e8de',
    profile: {
      followed: false,
      backgroundUrl: 'https://p3.music.126.net/TpJvKq8RzqjvLLGhnAirIg==/109951165243602387.jpg',
      detailDescription: '',
      accountStatus: 0,
      gender: 1,
      vipType: 11,
      userType: 0,
      avatarImgId: 109951165868686370,
      nickname: 'FishingFish26',
      backgroundImgId: 109951165243602380,
      birthday: 1097683200000,
      city: 110101,
      avatarUrl: 'https://p3.music.126.net/ubBzXMw7Of6PYQTKbkqnEw==/109951165868686362.jpg',
      defaultAvatar: false,
      province: 110000,
      expertTags: null,
      experts: {},
      mutual: false,
      remarkName: null,
      authStatus: 0,
      djStatus: 0,
      avatarImgIdStr: '109951165868686362',
      backgroundImgIdStr: '109951165243602387',
      description: '',
      userId: 297255927,
      signature: '花开花落终有时，但愿人间常有情。',
      authority: 0,
      avatarImgId_str: '109951165868686362',
      followeds: 14,
      follows: 47,
      eventCount: 8,
      avatarDetail: null,
      playlistCount: 10,
      playlistBeSubscribedCount: 1
    },
    bindings: [ [Object], [Object] ],
    cookie: '__remember_me=true; Max-Age=1296000; Expires=Sat, 30 Oct 2021 04:09:51 GMT; Path=/;;MUSIC_U=9af7d1ab111a6b5047512b0b1a33d74b078f5591542f65f43c394dd9ec20e203519e07624a9f0053d78b6050a17a35e705925a4e6992f61d07c385928f88e8de; Max-Age=1296000; Expires=Sat, 30 Oct 2021 04:09:51 GMT; Path=/;;NMTID=00OKj1IaaSER1Ik30NCs3w92nC3hmcAAAF8giRVxg; Max-Age=315360000; Expires=Mon, 13 Oct 2031 04:09:51 GMT; Path=/;;MUSIC_R_T=1467713309685; Max-Age=2147483647; Expires=Wed, 2 Nov 2089 07:23:58 GMT; Path=/;;__csrf=44a63102cd78a86608e65d22df7c3787; Max-Age=1296010; Expires=Sat, 30 Oct 2021 04:10:01 GMT; Path=/;;MUSIC_A_T=1467713293091; Max-Age=2147483647; Expires=Wed, 2 Nov 2089 07:23:58 GMT; Path=/;'
  },
  cookie: [
    '__remember_me=true; Max-Age=1296000; Expires=Sat, 30 Oct 2021 04:09:51 GMT; Path=/;',
    'MUSIC_U=9af7d1ab111a6b5047512b0b1a33d74b078f5591542f65f43c394dd9ec20e203519e07624a9f0053d78b6050a17a35e705925a4e6992f61d07c385928f88e8de; Max-Age=1296000; Expires=Sat, 30 Oct 2021 04:09:51 GMT; Path=/;',
    'NMTID=00OKj1IaaSER1Ik30NCs3w92nC3hmcAAAF8giRVxg; Max-Age=315360000; Expires=Mon, 13 Oct 2031 04:09:51 GMT; Path=/;',
    'MUSIC_R_T=1467713309685; Max-Age=2147483647; Expires=Wed, 2 Nov 2089 07:23:58 GMT; Path=/;',
    '__csrf=44a63102cd78a86608e65d22df7c3787; Max-Age=1296010; Expires=Sat, 30 Oct 2021 04:10:01 GMT; Path=/;',
    'MUSIC_A_T=1467713293091; Max-Age=2147483647; Expires=Wed, 2 Nov 2089 07:23:58 GMT; Path=/;'
  ]
}
      gender: 1,
      vipType: 11,
      userType: 0,
      avatarImgId: 109951165868686370,
      nickname: 'FishingFish26',
      backgroundImgId: 109951165243602380,
      birthday: 1097683200000,
      city: 110101,
      avatarUrl: 'https://p3.music.126.net/ubBzXMw7Of6PYQTKbkqnEw==/109951165868686362.jpg',
      defaultAvatar: false,
      province: 110000,
      expertTags: null,
      experts: {},
      mutual: false,
      remarkName: null,
      authStatus: 0,
      djStatus: 0,
      avatarImgIdStr: '109951165868686362',
      backgroundImgIdStr: '109951165243602387',
      description: '',
      userId: 297255927,
      signature: '花开花落终有时，但愿人间常有情。',
      authority: 0,
      avatarImgId_str: '109951165868686362',
      followeds: 14,
      follows: 47,
      eventCount: 8,
      avatarDetail: null,
      playlistCount: 10,
      playlistBeSubscribedCount: 1
    },
    bindings: [ [Object], [Object] ],
    cookie: '__remember_me=true; Max-Age=1296000; Expires=Sat, 30 Oct 2021 04:09:51 GMT; Path=/;;MUSIC_U=9af7d1ab111a6b5047512b0b1a33d74b078f5591542f65f43c394dd9ec20e203519e07624a9f0053d78b6050a17a35e705925a4e6992f61d07c385928f88e8de; Max-Age=1296000; Expires=Sat, 30 Oct 2021 04:09:51 GMT; Path=/;;NMTID=00OKj1IaaSER1Ik30NCs3w92nC3hmcAAAF8giRVxg; Max-Age=315360000; Expires=Mon, 13 Oct 2031 04:09:51 GMT; Path=/;;MUSIC_R_T=1467713309685; Max-Age=2147483647; Expires=Wed, 2 Nov 2089 07:23:58 GMT; Path=/;;__csrf=44a63102cd78a86608e65d22df7c3787; Max-Age=1296010; Expires=Sat, 30 Oct 2021 04:10:01 GMT; Path=/;;MUSIC_A_T=1467713293091; Max-Age=2147483647; Expires=Wed, 2 Nov 2089 07:23:58 GMT; Path=/;'
  },
  cookie: [
    '__remember_me=true; Max-Age=1296000; Expires=Sat, 30 Oct 2021 04:09:51 GMT; Path=/;',
    'MUSIC_U=9af7d1ab111a6b5047512b0b1a33d74b078f5591542f65f43c394dd9ec20e203519e07624a9f0053d78b6050a17a35e705925a4e6992f61d07c385928f88e8de; Max-Age=1296000; Expires=Sat, 30 Oct 2021 04:09:51 GMT; Path=/;',
    'NMTID=00OKj1IaaSER1Ik30NCs3w92nC3hmcAAAF8giRVxg; Max-Age=315360000; Expires=Mon, 13 Oct 2031 04:09:51 GMT; Path=/;',
    'MUSIC_R_T=1467713309685; Max-Age=2147483647; Expires=Wed, 2 Nov 2089 07:23:58 GMT; Path=/;',
    '__csrf=44a63102cd78a86608e65d22df7c3787; Max-Age=1296010; Expires=Sat, 30 Oct 2021 04:10:01 GMT; Path=/;',
    'MUSIC_A_T=1467713293091; Max-Age=2147483647; Expires=Wed, 2 Nov 2089 07:23:58 GMT; Path=/;'
  ]
}


可以看到确实登陆上了 但是无法正常使用登录后的功能

**Comment by k27dong** [comment]
关于‘登录后才可查看’的问题找到了，但是这是一个api的问题。。

我这个机器人的服务是基于[Binaryify/NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi)做的，然后我发现他们的issue里也提到了这个问题:

https://github.com/Binaryify/NeteaseCloudMusicApi/issues/1311
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/1346
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/1374

似乎是网易那边更改了'喜欢的音乐'这个歌单的格式，导致这个歌单不能像其他歌单一样处理了。[这个帖子](https://giters.com/DIYgod/RSSHub/issues/7686)里面说这个改动自六月初就有了。

目前好像没有什么解决方式，只能等api那边的作者修复了，很遗憾。

**Comment by k27dong** [comment]
另外那个vip歌曲播放的问题，查了一圈发现是我用的账号的黑胶vip过期了。

续费了就可以播放完整版了（之前`*p 徐佳莹 VIP`播放的是一个25秒的片段）。

**Comment by zhongzi26** [comment]
> 关于‘登录后才可查看’的问题找到了，但是这是一个api的问题。。
> 
> 我这个机器人的服务是基于[Binaryify/NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi)做的，然后我发现他们的issue里也提到了这个问题:
> 
> [Binaryify/NeteaseCloudMusicApi#1311](https://github.com/Binaryify/NeteaseCloudMusicApi/issues/1311) [Binaryify/NeteaseCloudMusicApi#1346](https://github.com/Binaryify/NeteaseCloudMusicApi/issues/1346) [Binaryify/NeteaseCloudMusicApi#1374](https://github.com/Binaryify/NeteaseCloudMusicApi/issues/1374)
> 
> 似乎是网易那边更改了'喜欢的音乐'这个歌单的格式，导致这个歌单不能像其他歌单一样处理了（而且登不登陆都会有这个报错）。[这个帖子](https://giters.com/DIYgod/RSSHub/issues/7686)里面说这个改动自六月初就有了。
> 
> 目前好像没有什么解决方式，只能等api那边的作者修复了，很遗憾。
> 
> 有其他的歌单会出现这个问题吗？

目前没有发现其他歌单有这个问题了，原来如此 我习惯性就用第一个歌单去测试 结果已测试就有问题😂

**Comment by zhongzi26** [comment]
> 关于‘登录后才可查看’的问题找到了，但是这是一个api的问题。。
> 
> 我这个机器人的服务是基于[Binaryify/NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi)做的，然后我发现他们的issue里也提到了这个问题:
> 
> [Binaryify/NeteaseCloudMusicApi#1311](https://github.com/Binaryify/NeteaseCloudMusicApi/issues/1311) [Binaryify/NeteaseCloudMusicApi#1346](https://github.com/Binaryify/NeteaseCloudMusicApi/issues/1346) [Binaryify/NeteaseCloudMusicApi#1374](https://github.com/Binaryify/NeteaseCloudMusicApi/issues/1374)
> 
> 似乎是网易那边更改了'喜欢的音乐'这个歌单的格式，导致这个歌单不能像其他歌单一样处理了（而且登不登陆都会有这个报错）。[这个帖子](https://giters.com/DIYgod/RSSHub/issues/7686)里面说这个改动自六月初就有了。
> 
> 目前好像没有什么解决方式，只能等api那边的作者修复了，很遗憾。
> 
> 有其他的歌单会出现这个问题吗？

不过console.log(`User: ${login_q.body.profile.nickname}`)这句似乎没有输出 或许是语法错误？ 没有学过这个语言不太清楚
